# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "f41dd3deba3be494ebc929848f5ad586"
application_url = "https://68e0-2a09-bac1-7ae0-68-00-245-11b.ngrok-free.app"
embedded = true
name = "pod"
handle = "pod-25"

[build]
include_config_on_deploy = true
automatically_update_urls_on_dev = true

[webhooks]
api_version = "2025-01"

  [[webhooks.subscriptions]]
  topics = [ "app/uninstalled" ]
  uri = "/webhooks/app/uninstalled"

  [[webhooks.subscriptions]]
  topics = [ "app/scopes_update" ]
  uri = "/webhooks/app/scopes_update"

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "write_products"

[auth]
redirect_urls = [
  "https://68e0-2a09-bac1-7ae0-68-00-245-11b.ngrok-free.app/auth/callback",
  "https://68e0-2a09-bac1-7ae0-68-00-245-11b.ngrok-free.app/auth/shopify/callback",
  "https://68e0-2a09-bac1-7ae0-68-00-245-11b.ngrok-free.app/api/auth/callback"
]

[pos]
embedded = false
